name: Publish packages to npm

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm -r \
            --filter "./packages/*" \
            build

      - name: Check package contents
        run: |
          pnpm -r \
            --filter "./packages/*" \
            pack --dry-run

      - name: Publish packages
        run: |
          pnpm -r \
            --filter "./packages/*" \
            publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
